casegreen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('huadmin/', admin.site.urls,name="huadmin"),
    path("accounts/", include("django.contrib.auth.urls"),name="login"),  # new
    path('', include('mycase.urls',namespace="casegreen"),name="home"),

    path('mycase/', include('mycase.urls',namespace="mycase"),name="home"),
    path('ioe/', include('ioe.urls',namespace="ioe"),name="home"),
    path('ctrlpanel/', include('ctrlpanel.urls',namespace="ctrlpanel"),name="home"),

]
app_name = 'casegreen'

ctrlpanel/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='ctrlhome'),
    path('dashbord/', views.ctrl_dashbord, name='ctrldashbord'),
    path('login/', views.login_view, name='ctrllogin'),
    path('exportdb/', views.exportDB, name='ctrlexportdb'),
    path('checkcase/', views.checkcase, name='ctrlcheckcase'),

    path('checkcase/checkcase_query', views.checkcase_query, name='checkcase_query'),
    path('checkcase/checkcase_update', views.checkcase_update, name='checkcase_update'),
    path('checkcase/checkcase_del', views.checkcase_del, name='checkcase_del'),

    path('ajax/sysupdate', views.sysupdate, name='sysupdate'),
    path('ajax/centerrun', views.centerrun, name='centerrun'),
    path('ajax/sysinit', views.sysinit, name='sysinit'),
    path('ajax/centerstatus', views.centerstatus, name='centerstatus'),

]

app_name = 'ctrlpanel'

ioe/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='ioehome'),
]

app_name = 'ioe'

ctrlpanel/views.py
import csv
from datetime import datetime,timedelta
import json
import os

from django.contrib.auth import authenticate, login
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404,HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test

from ctrlpanel.functions.utils import bkp_table, run_initalization, run_center
from ioe.functions.utils import run_center_ioe, generate_overview_ioe
from mycase.functions.utils import generate_overview
from mycase.models import *

center_dict = {"lin_lb": case_status_lin_lb,
               "msc_lb": case_status_msc_lb,
               "src_lb": case_status_src_lb,
               "wac_lb": case_status_wac_lb,
               "eac_lb": case_status_eac_lb,
               "ysc_lb": case_status_ysc_lb,
               "lin_sc": case_status_lin_sc,
               "msc_sc": case_status_msc_sc,
               "src_sc": case_status_src_sc,
               "wac_sc": case_status_wac_sc,
               "eac_sc": case_status_eac_sc,
               "ysc_sc": case_status_ysc_sc,
               "ioe": case_status_ioe
               }


# Create your views here.
@login_required()
def index(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    sys_params,created = sysparam.objects.get_or_create(pk=1,defaults={
        "centers": "LIN,MSC,SRC,EAC,WAC,YSC",
        "fiscal_year_n": 3,
        "crawler_time": "21:05",
        "crawler_number": 1,
        "sys_status": "Running"
    })
    sys_params.crawler_time = sys_params.crawler_time.strftime("%H:%M")
    context = {'sys_params': sys_params}
    return render(request,'ctrlpanel/index.html',context)

@login_required()
# @user_passes_test(lambda u: u.is_superuser)
def ctrl_dashbord(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    return render(request,'ctrlpanel/dashbord.html')


def login_view(request):
    username = password = ''
    next_url=""
    if request.GET:
        next_url = request.GET.get("next")

    if request.POST:
        username = request.POST['username']
        password = request.POST['passwd']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # print(next_url)
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect("ctrlpanel:ctrlhome")
            else:
                state = "Your account is not active, please contact the site admin."
                return HttpResponse(state)
        else:
            state = "Your username and/or password were incorrect."
            return HttpResponse(state)
    else:
        return redirect("login")



def exportDB(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="exportDB.csv"'
    # the csv writer
    writer = csv.writer(response, delimiter=",")

    case_status_tables = [case_status_lin_lb, case_status_msc_lb, case_status_src_lb, case_status_wac_lb,
                          case_status_eac_lb, case_status_ysc_lb,
                          case_status_lin_sc, case_status_msc_sc, case_status_src_sc, case_status_wac_sc,
                          case_status_eac_sc, case_status_ysc_sc,
                          case_status_ioe]
    model_ls = [sysparam, status, status_daily,form,center_running] + case_status_tables
    for m_i in model_ls:

        queryset = m_i.objects.all()
        model = queryset.model
        table_name = model._meta.db_table
        model_fields = model._meta.fields + model._meta.many_to_many
        field_names = [field.name for field in model_fields]
        # Write a first row for the Table name
        writer.writerow(["##"+table_name])
        # Write a row with header information
        writer.writerow(field_names)
        # Write data rows
        for row in queryset:
            values = []
            for field in field_names:
                value = getattr(row, field)
                if callable(value):
                    try:
                        value = value() or ''
                    except:
                        value = 'Error retrieving value'
                if value is None:
                    value = ''
                values.append(value)
            writer.writerow(values)
    return response

def sysinit(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    if request.method == "POST":
        # try:
        # backup data
        case_status_tables = [case_status_lin_lb, case_status_msc_lb, case_status_src_lb, case_status_wac_lb,
                              case_status_eac_lb, case_status_ysc_lb,
                              case_status_lin_sc, case_status_msc_sc, case_status_src_sc, case_status_wac_sc,
                              case_status_eac_sc, case_status_ysc_sc,
                              case_status_ioe]
        model_ls = [sysparam, status, status_daily, form, center_running] + case_status_tables
        for m_i in model_ls:
            pass
            # data = bkp_table(request, m_i.objects.all())
        #
        # Init
        run_initalization(request)
        return HttpResponse("OK")
        # except Exception as e:
        #     return HttpResponse(e)

def sysupdate(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    if request.method == "POST":
        # get the data from the client side.
        centers = request.POST.get("centers", None)
        fys_n = request.POST.get("fys", None)
        crawler_t = request.POST.get("crawler_t", None)+":00"
        crawler_n = request.POST.get("crawler_n", None)

        sys_params,created = sysparam.objects.update_or_create(pk=1,defaults={
            "centers":centers,
            "fiscal_year_n": fys_n,
            "crawler_time":crawler_t,
            "crawler_number": crawler_n
        })

        return HttpResponse("OK")

def centerrun(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    ## delete the static files
    file_ls = os.listdir("mycase/data/statistics/center_range_count")
    for f_i in file_ls:
        while True:
            try:
                os.remove("mycase/data/statistics/center_range_count/" + f_i)
                break
            except OSError:
                pass
    ##
    file_ls = os.listdir("mycase/data/statistics/center_range_count_heatmap")
    for f_i in file_ls:
        while True:
            try:
                os.remove("mycase/data/statistics/center_range_count_heatmap/" + f_i)
                break
            except OSError:
                pass
    ##
    file_ls = os.listdir("mycase/data/statistics/center_rd_count")
    for f_i in file_ls:
        while True:
            try:
                os.remove("mycase/data/statistics/center_rd_count/" + f_i)
                break
            except OSError:
                pass

    if request.method == "POST":
        # get the data from the client side.
        centers = request.POST.get("centers", None)
        center_ls = centers.split(",")
        for center_i in center_ls:
            try:
                center_running.objects.filter(center_lsi=center_i.upper()).update(status="Pend")
            except Exception as e:
                pass

        if "ioe0" in center_ls or "IOE0" in center_ls:
            center_ls = ["IOE"]

        for center_i in center_ls:
            if center_i == "IOE":
                return_code = run_center_ioe(request,center_i)
            else:
                return_code = run_center(request,center_i)

            if "skip" in return_code.lower():
                continue
            if "error" in return_code.lower():
                return HttpResponse(return_code)

        ####
        print("-------------------------------")
        print("Generate overview...")
        if center_i == "IOE":
            generate_overview_ioe()
        else:
            generate_overview(center_ls)
        print(centers)
        print("Generate overview... Done!")

        print("*******************************")
        print("All done!")
        print("*******************************")
        return HttpResponse("OK")

def centerstatus(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    qs_json = {}
    if request.method == "POST":
        center_status = center_running.objects.all()
        qs_json = serializers.serialize('json', center_status)

    return HttpResponse(qs_json, content_type='application/json')


def checkcase(request):
    if (not request.user.is_authenticated) or (not request.user.is_superuser):
        return redirect("ctrlpanel:ctrllogin")
        # return HttpResponse("Login: Please Login!")

    if request.method == "GET":
        return render(request,'ctrlpanel/ctrlcheckcase.html')
    elif request.method == "POST":
        return render(request,'ctrlpanel/ctrlcheckcase.html')


def checkcase_query(request):

ctrlpanel/templates/ctrl_basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Control panel</title>
    <link rel="stylesheet" href={% static "ctrlpanel/css/jquery-clockpicker.min.css" %} >
  <link rel="stylesheet" href={% static "css/mdb.min.css" %} >
  <link rel="stylesheet" href={% static "css/all.min.css" %} >
  <link rel="stylesheet" href={% static "ctrlpanel/css/style.css" %} >
  <script type="text/javascript" src={% static "js/jquery-3.6.0.min.js" %}></script>
</head>

  <body>
    <!--Main Navigation-->
    <header>
      <!-- Sidebar -->
      <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
        <div class="position-sticky">
          <div class="list-group list-group-flush mx-3 mt-4">
              {% url 'ctrlpanel:ctrlhome' as url %}
              <a href="{{ url }}" class="list-group-item list-group-item-action py-2 ripple {% if request.path == url %}active{% endif %}">
                <i class="fa-solid fa-sliders fa-fw me-3"></i><span>Control center</span>
              </a>
              {% url 'ctrlpanel:ctrlcheckcase' as url %}
              <a href="{{ url }}" class="list-group-item list-group-item-action py-2 ripple {% if request.path == url %}active{% endif %}">
                <i class="fa-solid fa-clipboard fa-fw me-3"></i><span>Check case</span>
              </a>

              {% url 'admin:index' as url %}
              <a href="{{ url }}" class="list-group-item list-group-item-action py-2 ripple {% if request.path == url %}active{% endif %}" target="_blank">
                <i class="fa-solid fa-database fa-fw me-3"></i><span>Database admin</span>
              </a>

              {% url 'casegreen:home' as url %}
              <a href="{{ url }}" class="list-group-item list-group-item-action py-2 ripple {% if request.path == url %}active{% endif %}" target="_blank">
                <i class="fa-solid fa-house fa-fw me-3"></i></i><span>Go to website</span>
              </a>
{#              <a href="#" class="list-group-item list-group-item-action py-2 ripple">#}
{#                <i class="fas fa-chart-area fa-fw me-3"></i><span>Webiste traffic</span>#}
{#              </a>#}
{#              <a href="#" class="list-group-item list-group-item-action py-2 ripple">#}
{#                  <i class="fas fa-lock fa-fw me-3"></i><span>Password</span>#}
{#              </a>#}
{#              <a href="#" class="list-group-item list-group-item-action py-2 ripple">#}
{#                  <i class="fas fa-chart-line fa-fw me-3"></i><span>Analytics</span>#}
{#              </a>#}
{#              <a href="#" class="list-group-item list-group-item-action py-2 ripple">#}
{#                  <i class="fas fa-calendar fa-fw me-3"></i><span>Calendar</span>#}
{#              </a>#}
{#              <a href="#" class="list-group-item list-group-item-action py-2 ripple">#}
{#                  <i class="fas fa-users fa-fw me-3"></i><span>Users</span>#}
{#              </a>#}
          </div>
        </div>
      </nav>
      <!-- Sidebar -->

      <!-- Navbar -->
      <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
        <!-- Container wrapper -->
        <div class="container-fluid">
          <!-- Toggle button -->
          <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-bars"></i>
          </button>

          <!-- Brand -->
          <a class="navbar-brand" href="#">
            <img src={% static "ctrlpanel/img/mycase_logo_short.png" %} height="32" alt="" loading="lazy"/>
          </a>

          <!-- Right links -->
          <ul class="navbar-nav ms-auto d-flex flex-row">
            <!-- Notification dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-bell"></i>
                <span class="badge rounded-pill badge-notification bg-danger">1</span>
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="#">Some news</a></li>
                <li><a class="dropdown-item" href="#">Another news</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>

            <!-- Icon -->
            <li class="nav-item">
              <a class="nav-link me-3 me-lg-0" href="#"><i class="fas fa-fill-drip"></i></a>
            </li>
            <!-- Icon -->
            <li class="nav-item me-3 me-lg-0">
              <a class="nav-link" href="#"> <i class="fab fa-github"></i> </a>
            </li>

            <!-- Avatar -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                <img src="https://mdbootstrap.com/img/Photos/Avatars/img (31).jpg" class="rounded-circle" height="22" alt="" loading="lazy"/>
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="#">My profile</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}"}>Logout</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- Container wrapper -->
      </nav>
      <!-- Navbar -->
    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main style="margin-top: 50px">
      <div class="container-fluid pt-4">
          <div class="row pb-3">
            <div class="col-md-12 grid-margin">
              <div class="d-flex justify-content-between flex-wrap">
                <div class="d-flex align-items-end flex-wrap">
                  <div class="me-md-3 me-xl-5">
                    <h2>Good
                        {% now "H" as current_time %}
                        {% if current_time|add:"0" >= 18 %} evening {% elif current_time|add:"0" >= 12 %} afternoon {% else %}morning {% endif %} ...</h2>
                    <p class="mb-md-0">This is the control center for updating the data.</p>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-end flex-wrap">
                    <button type="button" class="btn btn-light bg-white btn-icon me-3" onclick="location.reload()">
                        <i class="fa-solid fa-rotate-right fa-lg text-muted"></i>
                    </button>
                    <a class="btn btn-primary me-3 mt-2 mt-xl-0" id="exportdb" href="{% url "ctrlpanel:ctrlexportdb" %}">Export DB</a>
                    <button class="btn btn-danger me-3 mt-2 mt-xl-0" id="initsys" onclick="sysinit()">Initialization&nbsp;&nbsp;
                        <span class="spinner-border spinner-border-sm d-none" id="init_spinner" role="status" aria-hidden="true"></span>
                    </button>
                </div>
              </div>
            </div>
        </div>
          {% block content %}
          {% endblock %}
      </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer></footer>
    <!--Footer-->

    <!-- MDB -->
    <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>
  </body>

</html>