casegreen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('huadmin/', admin.site.urls,name="huadmin"),
    path("accounts/", include("django.contrib.auth.urls"),name="login"),  # new
    path('', include('mycase.urls',namespace="casegreen"),name="home"),

    path('mycase/', include('mycase.urls',namespace="mycase"),name="home"),
    path('ioe/', include('ioe.urls',namespace="ioe"),name="home"),
    path('ctrlpanel/', include('ctrlpanel.urls',namespace="ctrlpanel"),name="home"),

]
app_name = 'casegreen'

ioe/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='ioehome'),
]

app_name = 'ioe'

mycase/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('mycase/', views.mycase, name='mycase'),
    path('dashborddaily/', views.dashborddaily, name='dashborddaily'),
    path('dashbordajax/', views.dashbordajax, name='dashbordajax'),
    path('overview/', views.overview, name='overview'),
    path('processrn/', views.processrn, name='processrn'),
    path('processrd/', views.processrd, name='processrd'),
    path('summaryrn/', views.summaryrn, name='summaryrn'),
    path('summaryrd/', views.summaryrd, name='summaryrd'),
    path('processajax/', views.processajax, name='processajax'),
    path('countscalendar/', views.countscalendar, name='countscalendar'),
    path('queryrn/', views.queryrn, name='queryrn'),
    path('queryrd/', views.queryrd, name='queryrd'),
    path('today/', views.todaycounts, name='today'),
    path('nextstatus/', views.nextstatus, name='nextstatus'),
    path('about/', views.about, name='about'),
    path('comments/', views.comments, name='comments'),
    path('statuslist/', views.statuslist, name='statuslist'),

    path('ajax/caseinrange', views.caseinrange, name = "caseinrange"),
    path('ajax/mynextstatus', views.mynextstatus, name = "mynextstatus"),
    path('ajax/dailyrecords', views.dailyrecords, name = "dailyrecords"),
    path('ajax/rnrangecount', views.rnrangecount, name = "rnrangecount"),
    path('ajax/getsankey', views.getsankey, name = "getsankey"),
    path('ajax/todaymodalcasetable', views.todaymodalcasetable, name = "todaymodalcasetable"),
    path('ajax/ajax_queryrn', views.ajax_queryrn, name = "ajax_queryrn"),
    path('ajax/ajax_queryrd', views.ajax_queryrd, name = "ajax_queryrd"),
]

app_name = 'mycase'

mycase/views.py
import json
import os
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from mycase.functions.utils import *
from mycase.models import *

# Create your views here.
center_dict = {"lin_lb": case_status_lin_lb,
               "msc_lb": case_status_msc_lb,
               "src_lb": case_status_src_lb,
               "wac_lb": case_status_wac_lb,
               "eac_lb": case_status_eac_lb,
               "ysc_lb": case_status_ysc_lb,
               "lin_sc": case_status_lin_sc,
               "msc_sc": case_status_msc_sc,
               "src_sc": case_status_src_sc,
               "wac_sc": case_status_wac_sc,
               "eac_sc": case_status_eac_sc,
               "ysc_sc": case_status_ysc_sc,
               "ioe": case_status_ioe
               }

color20 = {'Received': '#1266f1', 'Transferred': '#17becf', 'Pending': '#ff7f0e',
           'FP_Scheduled': '#1f77b4', 'FP_Taken': '#aec7e8', 'InterviewScheduled': '#9467bd',
           'InterviewCompleted': '#c5b0d5','RFE_Sent': '#bcbd22', 'RFE_Received': '#dbdb8d',
           'Approved': '#2ca02c', 'Produced': '#98df8a','Mailed': '#a1d99b',
           'Hold': '#ffbb78', 'ReturnHold': '#8c564b', 'NoticeSent': '#c49c94', 'Reopened': '#e377c2',
           'Other': '#f7b6d2','Rejected': '#d62728', 'Terminated': '#ff9896',
           'bk1': '#7f7f7f', 'bk2': '#c7c7c7', 'bk3': '#9edae5'}

color8 = {'Received': "#1072f1", 'FP_Taken': "#11a9fa", 'Interviewed': "#2b04da", 'RFE': "#f4b824",
          'Transferred': "#c77cff", 'Approved': "#1db063", 'Rejected': "#ff001a", 'Other': "#78787a"}

# rd_status = ["Fees Were Waived", "Card Was Received By USCIS Along With My Letter", "Case Accepted By The USCIS Lockbox",
#              "Case Was Received", "Case Was Received and A Receipt Notice Was Sent", "Case Was Received At Another USCIS Office",
#              "Document and Letter Was Received", "Document And Letter Was Received And Under Review",
#              "Fingerprint Fee Was Received","Immigrant Visa Fee Payment Received"]

rd_status = get_rd_status()

def index(request):
    return render(request, 'index.html')

def mycase(request):
    if request.method == "GET":
        receipt_num = request.GET.get("receipt_number", None)
    elif request.method == "POST":
        receipt_num = request.POST.get("receipt_number", None)

    if receipt_num is None or receipt_num.strip() == "":
        return redirect("casegreen:home")

    receipt_num = receipt_num.strip()
    center = receipt_num[:3]
    year = receipt_num[3:5]
    lb_sc = "LB" if receipt_num[5] == "9" else "SC"

    ## try to get real-time data from uscis
    try:
        status_ls = get_status(receipt_num)
        # print(status_ls)
    except Exception as e:
        # print(e)
        status_ls = []

    ## read exist data from database
    if center.upper()=="IOE":
        center_table = case_status_ioe
    else:
        center_table = center_dict[center.lower() + "_" + lb_sc.lower()]
    status_qs = center_table.objects.filter(receipt_number=receipt_num)
    if status_qs.exists():
        status_qs = status_qs.order_by("add_date")
        if len(status_ls) >= 3:
            try:
                time_x = datetime.strptime(status_ls[1], "%B %d, %Y").date()
            except Exception as e:
                time_x = datetime.now().date()

            days = (datetime.now().date() - time_x).days
            if status_ls[0] == "":
                status_ls[0] = status_qs.last().form
            if status_qs.last().status != status_ls[2]:
                l3_name = get_l_status(status_ls[2], "L3")

                if l3_name in ["Approved"]:
                    case_stage = "Approved"
                elif l3_name in ["Rejected"]:
                    case_stage = "Rejected"
                elif l3_name in ["RFE"]:
                    case_stage = "RFE"
                else:
                    case_stage = "Processing"

                new_status = center_table.objects.create(receipt_number=receipt_num,
                                                         form=status_ls[0],
                                                         status=status_ls[2],
                                                         action_date=status_ls[1],
                                                         action_date_x=time_x,
                                                         case_stage=case_stage,
                                                         add_date=datetime.now(),
                                                         date_number=(datetime.now() - datetime(2000, 1, 1)).days)
                new_status.save()
                status_qs = center_table.objects.filter(receipt_number=receipt_num).order_by("add_date")
            else:
                pass
        else:
            status_ls = [status_qs.last().form, status_qs.last().action_date_x, status_qs.last().status, ""]
            time_x = status_qs.last().action_date_x
            days = (datetime.now().date() - time_x).days
    else:
        if len(status_ls) < 3:
            status_ls = ["NA", "NA", "Cannot get the data!", ""]
            days = "NA"
        else:
            ## Case is valid but does not exist in database
            if receipt_num.startswith("IOE"):
                with open("mycase/data/crawler/ioetoadd/" + receipt_num, 'w') as fp:
                    pass

            time_x = datetime.strptime(status_ls[1], "%B %d, %Y")
            days = (datetime.now() - time_x).days
            l3_name = get_l_status(status_ls[2], "L3")

            rd_date = date(2000, 1, 1)
            fy_x = 2000
            if status_ls[2] in rd_status:
                rd_date = time_x
                fy_x = rd_date.year
                if rd_date.month > 9: fy_x += 1
            else:
                if receipt_num.startswith("IOE"):
                    pass
                else:
                    fy_x =int(receipt_num[3:5])+2000

            if l3_name in ["Approved"]:
                case_stage = "Approved"
            elif l3_name in ["Rejected"]:
                case_stage = "Rejected"
            elif l3_name in ["RFE"]:
                case_stage = "RFE"
            else:
                case_stage = "Processing"

            new_status = center_table.objects.create(receipt_number=receipt_num,
                                                     form=status_ls[0],
                                                     status=status_ls[2],
                                                     action_date=status_ls[1],
                                                     action_date_x=time_x,
                                                     case_stage=case_stage,
                                                     add_date=datetime.now(),
                                                     date_number=(datetime.now() - datetime(2000, 1, 1)).days,
                                                     rd_date=rd_date,
                                                     fiscal_year=fy_x)
            new_status.save()
            status_qs = center_table.objects.filter(receipt_number=receipt_num).order_by("add_date")

    case_range_s = int(receipt_num[3:]) - int(int(receipt_num[3:]) % 5000)
    case_range_e = case_range_s + 4999

    form_ls = []
    if status_ls[0] == "":
        ## form type is not available
        form_qs = form.objects.all()
        form_ls = [form_i.code for form_i in form_qs]

    context = {
        "status": {'form': status_ls[0], 'date': status_ls[1], 'status': status_ls[2], 'status_text': status_ls[3],"days": days},
        "receipt_num": receipt_num, "case_range": str(case_range_s) + "-" + str(case_range_e), "form_ls": form_ls,
        "status_qs": status_qs, "page_title": "myCase"}
    return render(request, 'mycase/mycase.html', context)


def caseinrange(request):
    # request should be ajax and method should be GET.
    if request.method == "GET":
        # get the data_type from the client side.
        receipt_num = request.GET.get("recepit_num", None)
        form_type = request.GET.get("form_type", None)
        case_range = request.GET.get("case_range", None)
        selectform = request.GET.get("selectform", None)

        delta_1d = datetime.today().date() + timedelta(days=-2)
        delta_1w = datetime.today().date() + timedelta(days=-8)
        delta_2w = datetime.today().date() + timedelta(days=-15)

        if form_type == "":
            data_dict = {"n_cases": 0, "message": "Form type is not available!"}
            return JsonResponse(data_dict, status=200)

        # check for the data_type.
        if receipt_num is not None:
            center = receipt_num[:3]
            year = receipt_num[3:5]
            lb_sc = "LB" if receipt_num[5] == "9" else "SC"
            if center.upper() == "IOE":
                center_table = case_status_ioe
            else:
                center_table = center_dict[center.lower() + "_" + lb_sc.lower()]

            if selectform == "yes" and form_type != "":
                case_x = center_table.objects.filter(receipt_number=receipt_num).order_by("-add_date").first()
                case_x.form = form_type
                case_x.save()

            case_range_base = int(receipt_num[3:]) - int(int(receipt_num[3:]) % 5000)
            case_qs = getcase_in_range(case_range, center, case_range_base, center_table, form_type, receipt_num)

            ##########
            # print(len(case_qs))
            if len(case_qs) > 0:
                status_letter = {"Received": "R", "FP_Taken": "F", "Interviewed": "I", "RFE": "E", "Transferred": "T",
                                 "Approved": "A", "Rejected": "J", "Other": "O"}
                status_abbr = {"Received": "REC", "FP_Taken": "FP", "Interviewed": "ITV", "RFE": "RFE",
                               "Transferred": "TRF", "Approved": "APV", "Rejected": "RJC", "Other": "OTH"}

mycase/templates/mycase_basic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="A project for Visa status tracking and prediction. Overview of USCIS visa processing. USCIS case status progress data visualization.">
    <meta name="keywords" content="Immigrants, USCIS, Case status, Visa application, Visa status statistics, Visa status prediction, Green Card, I-129, I-130, I-131, I-140, I-485, I-765, EAD, H-1B">
    <meta name="author" content="CaseGreen">
    <title>{{page_title}}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "css/all.min.css" %} >
    <!-- MDB -->
    <link rel="stylesheet" href={% static "css/mdb.min.css" %} >
    <!-- Custom styles -->
    <link rel="stylesheet" id="theme_css" href={% static "mycase/css/style_white_bg.css" %} >
    <link rel="stylesheet" id="theme_css" href={% static "mycase/css/mystyle.css" %} >
    <script type="text/javascript" src={% static "js/jquery-3.6.0.min.js" %}></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
    <script src="{% static "js/echarts.min.js" %}"></script>

</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v15.0" nonce="A2tFf1Rw"></script>
<div class="main_content">
  <div id="content-wrap">
    <div class="container-fluid" style="width: 100%; min-width: 1200px;">
        <div class="top-banner" style="height: 40px;" >
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg">
              <!-- Container wrapper -->
              <div class="container-fluid">
                <!-- Collapsible wrapper -->
                <div class="row">
                  <ul class="navbar-nav mb-2 mb-lg-0">
                      <li class="nav-item"><a class="nav-link" href="{% url "casegreen:about" %}">About</a></li>
                       <!-- Dropdown -->
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"  href="#" id="resoursDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">Resources</a>
                        <ul class="dropdown-menu" aria-labelledby="resoursDropdown">
                            <li><a class="dropdown-item" href="https://travel.state.gov/content/travel/en/legal/visa-law0/visa-bulletin.html" target="_blank">Visa Bulletin</a></li>
                            <li><a class="dropdown-item" href="https://ebgreencard.com/" target="_blank">EB/485 wiki</a></li>
                        </ul>
                      </li>
                      {# <li class="nav-item"><a class="nav-link"href={% url "mycase:dashborddaily" %}>Dashbord</a></li>#}
                      <!-- Dropdown -->
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"  href="#" id="dashDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">Dashbords</a>
                        <ul class="dropdown-menu" aria-labelledby="dashDropdown">
                          <li><a class="dropdown-item" href={% url "mycase:dashborddaily" %}>Status daily</a></li>
                          <li><a class="dropdown-item" href={% url "mycase:overview" %}>Center/Forms/Status</a></li>
                        </ul>
                      </li>
                      {# <li class="nav-item"><a class="nav-link" href={% url "casegreen:process" %}>Process</a></li>#}
                      <!-- Dropdown -->
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"  href="#" id="processDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">Process</a>
                        <ul class="dropdown-menu" aria-labelledby="processDropdown">
                          <li><a class="dropdown-item" href={% url "mycase:processrn" %}>By receipt number(RN)</a></li>
                          <li><a class="dropdown-item" href={% url "mycase:processrd" %}>By received date(RD)</a></li>
                            <li><a class="dropdown-item" href={% url "mycase:countscalendar" %}>Counts calendar</a></li>
                        </ul>
                      </li>
                       <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"  href="#" id="summaryDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">Summary</a>
                            <ul class="dropdown-menu" aria-labelledby="summaryDropdown">
                              <li><a class="dropdown-item" href="{% url "mycase:summaryrn" %}">By receipt number(RN)</a></li>
                              <li><a class="dropdown-item" href="{% url "mycase:summaryrd" %}">By received date(RD)</a></li>
                            </ul>
                       </li>
                      {#<li class="nav-item"><a class="nav-link" href="{% url "mycase:queryrn" %}">Query</a></li>#}
                      <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"  href="#" id="queryDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">Query</a>
                            <ul class="dropdown-menu" aria-labelledby="queryDropdown">
                              <li><a class="dropdown-item" href="{% url "mycase:queryrn" %}">By receipt number(RN)</a></li>
                              <li><a class="dropdown-item" href="{% url "mycase:queryrd" %}">By received date(RD)</a></li>
                            </ul>
                       </li>
                      <li class="nav-item"><a class="nav-link" href="{% url "casegreen:nextstatus" %}">NextStatus</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url "casegreen:today" %}">Today!</a></li>
                      <li class="nav-item"><a class="nav-link" href="{% url "casegreen:home" %}">myCase</a></li>
                  </ul>
                  <!-- Left links -->
                </div>
                <!-- Collapsible wrapper -->

                <!-- Right elements -->
                <div class="d-flex align-items-center">
                    <iframe id="datetime-iframe" src="https://free.timeanddate.com/clock/i8fs8off/n43/fs16/tct/pct/ahl/pd3/tt0/tw1/tm1/ta1" frameborder="0" width="326" height="21" allowtransparency="true"></iframe>

                  <!-- Icon -->
                  <a class="text-reset me-5" href="{% url "mycase:comments" %}" target="_blank"><i class="fa-solid fa-comments header-right-icon"></i></a>

                  <!-- Notifications -->
{#                  <div class="dropdown">#}
{#                    <a class="text-reset me-5 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">#}
{#                      <i class="fas fa-bell header-right-icon"></i>#}
{#                      <span class="badge rounded-pill badge-notification bg-danger">1</span>#}
{#                    </a>#}
{#                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">#}
{#                      <li><a class="dropdown-item" href="#">Some news</a></li>#}
{#                      <li><a class="dropdown-item" href="#">Another news</a></li>#}
{#                      <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#                    </ul>#}
{#                  </div>#}
                    <!-- Icon setting-->
{#                        <div class="dropdown">#}
{#                            <a class="text-reset me-3 dropdown-toggle hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">#}
{#                                <i class="fa-solid fa-sliders header-right-icon"></i>#}
{#                            </a>#}
{#                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink" >#}
{#                              <li><a class="dropdown-item" href="#" id="chbg_btn" onclick="change_theme()">Remove Background</a></li>#}
{#                            </ul>#}
{#                        </div>#}
                  <!-- Avatar -->
{#                  <div class="dropdown">#}
{#                    <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar" role="button" data-mdb-toggle="dropdown" aria-expanded="false">#}
{#                      <img src="{% static "mycase/img/alphabet/webp/unknow.webp" %}" class="rounded-circle" height="25" alt="Black and White Portrait of a Man" loading="lazy"/>#}
{#                    </a>#}
{#                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">#}
{#                      <li><a class="dropdown-item" href="#">My profile</a></li>#}
{#                      <li><a class="dropdown-item" href="#">Logout</a></li>#}
{#                    </ul>#}
{#                  </div>#}
                    <div class="fb-like" data-href="https://www.casegreen.info/" data-width="" data-layout="button_count" data-action="like" data-size="large" data-share="true"></div>
                </div>
                <!-- Right elements -->
              </div>
              <!-- Container wrapper -->
            </nav>
            <!-- Navbar -->
        </div>
        <hr style="height: 0.1px;color: #ccc">
    </div>

    {% block content %}

    {% endblock %}
  </div>
    <!-- Footer -->
    <footer class="text-center text-md-start bg-light text-muted" style="min-width: 820px;">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2022-Present Copyright:
        <a class="text-reset fw-bold" href="#">CaseGreen.info</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
</div>

</body>
<!-- MDB -->
    <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>

</html>